
import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '@/components/Layout/Header';
import Footer from '@/components/Layout/Footer';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params; 
    const messages = await getMessages();
  return (
    <html lang={locale} suppressHydrationWarning>
      <body suppressHydrationWarning>
        <NextIntlClientProvider messages={messages} locale={locale}>
          <div className="fixed inset-x-0 top-0 z-50  shadow-2xl bg-brand-primary text-white">
            <Header />
          </div>

          <main className="container mx-auto w-full max-w-6xl pt-20 pb-20 px-3 flex-1">
            {children}
          </main>

          <div className="fixed inset-x-0 bottom-0 z-50  shadow-2xl bg-brand-secondary backdrop-blur">
            <Footer />
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
